### ISSUE TITLE
Make bot work on production

### ISSUE THREAD

**Issue by nikosavola** [fyysikkokilta/fyysikkospeksi-taulubot#1]
#### Subtasks probably include:
- [x] Make a setup.py
- [x]  Setup Telegram BotFather
- [x]  Setup to work on DigitalOcean, Docker also possible, see #5 
  * Docker container could be general, i.e., such that it takes the API key as an *env* and frame as some sort of input

**Comment by nikosavola** [comment]
Docker tested on DigitalOcean with a `.env` file and restart policy as _unless-stopped_.
